import esbuild from "esbuild";
import fs from "node:fs/promises";
import { builtinModules } from "node:module";
import process from "node:process";

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source available at https://github.com/cavi-ai/claude-obsidian
*/`;

// Add the `node:`-prefixed variants so Node builtins used by the MCP server
// (http, etc.) are treated as external — they exist at runtime in Obsidian's
// Electron/Node environment (this is a desktop-only plugin).
const builtins = [...new Set(builtinModules.map((m) => m.replace(/^node:/, "")))];
const nodeBuiltins = [...builtins, ...builtins.map((m) => `node:${m}`)];

// Pass 1: bundle the embedding worker (transformers.js included) to a text
// artifact that the main bundle inlines and instantiates via a Blob URL.
// Note: built once per invocation — editing worker.ts requires restarting dev.
await esbuild.build({
  entryPoints: ["src/semantic/transformers/worker.ts"],
  bundle: true,
  format: "iife",
  target: "es2021",
  platform: "browser",
  outfile: ".build/embed-worker.txt",
  minify: prod,
  logLevel: "info",
});

// Pass 1b: the pdf.js worker, likewise inlined and Blob-URL'd at runtime (PDF
// text extraction for the semantic index).
await esbuild.build({
  entryPoints: ["node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs"],
  bundle: true,
  format: "iife",
  target: "es2021",
  platform: "browser",
  outfile: ".build/pdf-worker.txt",
  minify: true,
  logLevel: "info",
});

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2021",
  loader: { ".txt": "text" },
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  metafile: prod,
});

if (prod) {
  const result = await context.rebuild();
  await fs.writeFile(".build/meta.json", JSON.stringify(result.metafile));
  process.exit(0);
} else {
  await context.watch();
}
